"""initial schema

Revision ID: b4b881933eb1
Revises: 
Create Date: 2026-06-06 10:46:13.353062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4b881933eb1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('ats_score', sa.Integer(), nullable=True))
    op.add_column('applications', sa.Column('ats_result', sa.Text(), nullable=True))
    op.add_column('applications', sa.Column('pipeline_score', sa.Integer(), nullable=True))
    op.add_column('applications', sa.Column('pipeline_result', sa.Text(), nullable=True))
    op.add_column('applications', sa.Column('improvement_tips', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('required_skills', sa.JSON(), nullable=True))
    op.add_column('jobs', sa.Column('experience_min', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('experience_max', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('education_requirement', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('salary_range', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('job_type', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('work_mode', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('location', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('deadline', sa.DateTime(), nullable=True))
    op.add_column('jobs', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('jobs', sa.Column('ats_criteria', sa.JSON(), nullable=True))
    op.add_column('jobs', sa.Column('ats_threshold', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('ats_mode', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('ats_top_n', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('blind_hiring', sa.Boolean(), nullable=True))
    op.add_column('jobs', sa.Column('fraud_scan_result', sa.JSON(), nullable=True))
    op.add_column('jobs', sa.Column('is_flagged', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.drop_column('jobs', 'is_flagged')
    op.drop_column('jobs', 'fraud_scan_result')
    op.drop_column('jobs', 'blind_hiring')
    op.drop_column('jobs', 'ats_top_n')
    op.drop_column('jobs', 'ats_mode')
    op.drop_column('jobs', 'ats_threshold')
    op.drop_column('jobs', 'ats_criteria')
    op.drop_column('jobs', 'is_active')
    op.drop_column('jobs', 'deadline')
    op.drop_column('jobs', 'location')
    op.drop_column('jobs', 'work_mode')
    op.drop_column('jobs', 'job_type')
    op.drop_column('jobs', 'salary_range')
    op.drop_column('jobs', 'education_requirement')
    op.drop_column('jobs', 'experience_max')
    op.drop_column('jobs', 'experience_min')
    op.drop_column('jobs', 'required_skills')
    op.drop_column('applications', 'improvement_tips')
    op.drop_column('applications', 'pipeline_result')
    op.drop_column('applications', 'pipeline_score')
    op.drop_column('applications', 'ats_result')
    op.drop_column('applications', 'ats_score')
    # ### end Alembic commands ###
